name: Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: golang:1.16.3-buster
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: test
        run: go test -race ./...
